# Generated by Django 5.1.4 on 2024-12-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=100),
        ),
    ]
