# Generated by Django 5.1.4 on 2025-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_vehicle',
            name='level',
            field=models.CharField(choices=[('basement', 'Basement'), ('ground', 'Ground Floor'), ('first', 'First Floor'), ('second', 'Second Floor')], default='ground', max_length=20),
        ),
    ]
