# Generated by Django 5.1.4 on 2025-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_entry_vehicle_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_vehicle',
            name='level',
            field=models.CharField(choices=[('Basement', 'Basement'), ('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor')], default='ground', max_length=20),
        ),
    ]
