# Generated by Django 5.1.4 on 2025-01-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_entry_vehicle_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_vehicle',
            name='slot',
            field=models.CharField(default='Slot1', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry_vehicle',
            name='level',
            field=models.CharField(choices=[('Basement', 'Basement'), ('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor')], max_length=20),
        ),
    ]
