# Generated by Django 5.1.4 on 2025-01-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_entry_vehicle_slot_alter_entry_vehicle_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_vehicle',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry_vehicle',
            name='parking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
