# Generated by Django 5.1.4 on 2025-01-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_entry_vehicle_exit_time_entry_vehicle_parking_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry_vehicle',
            name='parking_fee',
        ),
    ]
