# Generated by Django 5.1.4 on 2025-01-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vehicle_exit',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.vehicleexit'),
            preserve_default=False,
        ),
    ]
