# Generated by Django 5.1.4 on 2025-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_payment_vehicle_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexit',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
