# Generated by Django 5.1.4 on 2025-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_vehicleexit_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
