# Generated by Django 5.1.4 on 2025-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_alter_entry_vehicle_plate_number'),
        ('parking', '0017_alter_entry_vehicle_plate_number'),
    ]

    operations = [
    ]
