# Generated by Django 5.1.4 on 2025-01-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_merge_20250114_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_vehicle',
            name='slot',
        ),
        migrations.AddField(
            model_name='entry_vehicle',
            name='parking_number',
            field=models.CharField(default='Park1', max_length=20),
        ),
    ]
