# Generated by Django 5.1.4 on 2025-01-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_number', models.CharField(max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.project')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tower'),
        ),
    ]
